version: "3"

services:
  tuic:
    build:
      context: .
      dockerfile: Dockerfile
    image: tuic:latest
    container_name: tuic
    volumes:
      - ./:/root/configs:ro
      - ./fullchain.pem:/root/cert/cert.crt:ro
      - ./privkey.pem:/root/cert/private.key:ro
    ports:
      - "${TUIC_PORT}:8880/udp"
      - "${TUIC_PORT}:8880/tcp"
    restart: unless-stopped
    privileged: true
