version: "3.9"
services:
  panel:
    image: hossinasaadi/x-ui
    restart: unless-stopped
    volumes:
        - ./fullchain.pem:/root/cert/cert.crt:ro
        - ./privkey.pem:/root/cert/private.key:ro
        - ./db/:/etc/x-ui/
    network_mode: "host"
